---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: upgrad-capstone
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upgrad-capstone
  template:
    metadata:
      name: upgrad-capstone
      labels:
        app: upgrad-capstone
    spec:
      containers:
        - name: upgrad-capstone
          image: 028725692999.dkr.ecr.us-east-1.amazonaws.com/upgrad-capstone:latest
          resources:
            requests:
              cpu: 800m
              memory: 400Mi
            limits:
              cpu: 1000m
              memory: 400Mi
          imagePullPolicy: Always
      tolerations:
        - key: "app"
          value: "upgrad-capstone"
          operator: "Equal"
          effect: "NoSchedule"
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst

---
kind: Service
apiVersion: v1
metadata:
  name: upgrad-capstone
  namespace: demo
spec:
  selector:
    app: upgrad-capstone
  type: LoadBalancer
  ports:
    - name: app-port
      protocol: TCP
      port: 80
      targetPort: 8081

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upgrad-capstone
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upgrad-capstone
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
